/**
 * Full-text search across the Theory of Everything document body.
 *
 * The curated `searchIndex` only covers pages/concepts/axioms. This module
 * lazily loads the prebuilt `/toe-search-index.json` (generated by
 * scripts/build-toe-search-index.mjs from toe-full.html) so the Ctrl+K palette
 * can also search the actual chapter text. Results deep-link into the Read
 * page, which scrolls its iframe to the matching heading.
 */

export interface ToeSection {
  /** Heading text — also the deep-link key (/read?goto=<encoded title>). */
  title: string;
  /** Heading level (1–3). */
  level: number;
  /** Short plain-text preview of the section body. */
  snippet: string;
  /** Lowercased title + body, used for matching. */
  text: string;
}

export interface ToeSearchResult extends ToeSection {
  score: number;
}

let cache: ToeSection[] | null = null;
let pending: Promise<ToeSection[]> | null = null;

/** Lazily fetch and cache the ToE full-text index. */
export async function loadToeIndex(): Promise<ToeSection[]> {
  if (cache) return cache;
  if (pending) return pending;
  pending = fetch("/toe-search-index.json")
    .then((res) => {
      if (!res.ok) throw new Error(`Failed to load ToE index: ${res.status}`);
      return res.json() as Promise<ToeSection[]>;
    })
    .then((data) => {
      cache = data;
      return data;
    })
    .catch((err) => {
      pending = null;
      throw err;
    });
  return pending;
}

export function searchToe(
  sections: ToeSection[],
  query: string,
  limit = 6,
): ToeSearchResult[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  const words = q.split(/\s+/).filter((w) => w.length >= 2);

  const scored: ToeSearchResult[] = [];
  for (const section of sections) {
    const titleLower = section.title.toLowerCase();
    let score = 0;

    if (titleLower.includes(q)) {
      score += 120;
      if (titleLower.startsWith(q)) score += 40;
    }
    if (section.text.includes(q)) score += 40;

    for (const word of words) {
      if (titleLower.includes(word)) score += 15;
      if (section.text.includes(word)) score += 5;
    }

    // Prefer higher-level headings (chapters over deep subsections).
    if (score > 0) {
      score += (4 - section.level) * 3;
      scored.push({ ...section, score });
    }
  }

  return scored.sort((a, b) => b.score - a.score).slice(0, limit);
}

/** Builds a snippet centred on the first query-term match for context. */
export function highlightSnippet(section: ToeSection, query: string): string {
  const q = query.toLowerCase().trim();
  const idx = section.snippet.toLowerCase().indexOf(q);
  if (idx <= 60 || q.length < 2) return section.snippet;
  return "…" + section.snippet.slice(idx - 40);
}
